eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
logging:
  level:
    io:
      seata: debug
server:
  port: 8084
spring:
  application:
    name: business-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

  datasource:
    password: Workshop123
    url: jdbc:mysql://rm-2zetd9474ydd1g5955o.mysql.rds.aliyuncs.com:3306/fescar?useSSL=false&serverTimezone=UTC
    username: workshop
  main:
    allow-bean-definition-overriding: true
