eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

logging:
  level:
    io:
      seata: debug
server:
  port: 8083

spring:
  application:
    name: account-service
  datasource:
    password: Workshop123
    url: jdbc:mysql://rm-2zetd9474ydd1g5955o.mysql.rds.aliyuncs.com:3306/fescar?useSSL=false&serverTimezone=UTC
    username: workshop
  main:
    allow-bean-definition-overriding: true

# 1.0新添加的enabled激活自动配置，使得我们可以在yaml/properties文件中配置，
# 避免了以前需要客户端引入2个文件：
# file.conf 和 registry.conf





